### ISSUE TITLE
Use request template for low cardinality on span name.

### ISSUE THREAD

**Issue by jcchavezs** [luoxiaojun1992/laravel-zipkin#1]
Currently, the span naming is leading to high cardinality by using the request path. Instead you should try to use something with low cardinality and predictable if possible. E.g. instead of using `/things/123456` you might want to use `/things/{thing_id}`
.
https://github.com/luoxiaojun1992/laravel-zipkin/blob/master/src/HttpClient.php#L33

**Comment by luoxiaojun1992** [comment]
Good suggestion. Fixed in #2 . Thanks.
